/**
 * Brief renderer — converts discovery session JSON to a markdown project brief.
 */

import type { DiscoverySession, RedFlagSeverity } from "./schemas/discovery";

const SEVERITY_EMOJI: Record<RedFlagSeverity, string> = {
  high: "🔴",
  medium: "🟡",
  low: "🔵",
};

/**
 * Render a discovery session to a markdown project brief.
 */
export function renderBrief(session: DiscoverySession): string {
  const lines: string[] = [];

  // Header
  lines.push(`# Project Brief: ${session.session.client_name}`);
  lines.push("");
  const started = new Date(session.session.started);
  const ended = session.session.ended
    ? new Date(session.session.ended)
    : new Date();
  const durationMin = Math.round(
    (ended.getTime() - started.getTime()) / 60000
  );
  lines.push(
    `**Date:** ${started.toISOString().slice(0, 10)} | **Duration:** ${durationMin} min`
  );
  lines.push("");

  // Project Summary
  if (session.brief.project_type) {
    lines.push("## Project Summary");
    lines.push("");
    lines.push(
      `**Type:** ${session.brief.project_type} | **Complexity:** ${session.brief.estimated_complexity}`
    );
    lines.push("");
  }

  // Key Requirements
  if (session.brief.key_requirements.length > 0) {
    lines.push("## Requirements");
    lines.push("");
    for (const req of session.brief.key_requirements) {
      lines.push(`- [ ] ${req}`);
    }
    lines.push("");
  }

  // Answered items (what we learned)
  const answered = session.checklist.filter((i) => i.status === "answered");
  if (answered.length > 0) {
    lines.push("## What We Learned");
    lines.push("");
    lines.push("| Category | Question | Answer |");
    lines.push("|----------|----------|--------|");
    for (const item of answered) {
      lines.push(`| ${item.category} | ${item.question} | ${item.answer} |`);
    }
    lines.push("");
  }

  // Open Questions
  if (session.brief.open_questions.length > 0) {
    lines.push("## Open Questions (need follow-up)");
    lines.push("");
    session.brief.open_questions.forEach((q, i) => {
      lines.push(`${i + 1}. ${q}`);
    });
    lines.push("");
  }

  // Red Flags
  if (session.red_flags.length > 0) {
    lines.push("## Red Flags");
    lines.push("");
    for (const flag of session.red_flags) {
      const emoji = SEVERITY_EMOJI[flag.severity];
      lines.push(`- ${emoji} **${flag.flag}** (${flag.severity})`);
      if (flag.suggestion) {
        lines.push(`  - Suggestion: ${flag.suggestion}`);
      }
    }
    lines.push("");
  }

  // Next Steps
  if (session.brief.recommended_next_steps.length > 0) {
    lines.push("## Recommended Next Steps");
    lines.push("");
    session.brief.recommended_next_steps.forEach((step, i) => {
      lines.push(`${i + 1}. ${step}`);
    });
    lines.push("");
  }

  // Footer
  lines.push("---");
  lines.push(
    `*Generated by Discovery Voice Golem on ${new Date().toISOString()}*`
  );
  lines.push("");

  return lines.join("\n");
}
