/**
 * Report renderer — converts QA session JSON to markdown.
 */

import type { QASession, QACheck, Severity } from "./schemas/checklist";

const SEVERITY_ORDER: Record<Severity, number> = {
  critical: 0,
  high: 1,
  medium: 2,
  low: 3,
  enhancement: 4,
};

const SEVERITY_EMOJI: Record<Severity, string> = {
  critical: "🔴",
  high: "🟠",
  medium: "🟡",
  low: "🔵",
  enhancement: "💡",
};

/**
 * Render a QA session to a markdown report string.
 */
export function renderReport(session: QASession): string {
  const lines: string[] = [];
  const siteName = new URL(session.session.url).hostname;

  // Header
  lines.push(`# QA Report: ${siteName}`);
  lines.push("");
  const started = new Date(session.session.started);
  const ended = session.session.ended
    ? new Date(session.session.ended)
    : new Date();
  const durationMin = Math.round(
    (ended.getTime() - started.getTime()) / 60000
  );
  lines.push(
    `**Date:** ${started.toISOString().slice(0, 10)} | **Duration:** ${durationMin} min | **Pages:** ${session.session.pages_checked}`
  );
  lines.push("");

  // Summary
  lines.push("## Summary");
  lines.push("");
  lines.push(`- ${session.summary.passed} checks passed`);
  lines.push(
    `- ${session.summary.failed} issues found${session.summary.critical_issues.length > 0 ? ` (${session.summary.critical_issues.length} critical)` : ""}`
  );
  if (session.summary.skipped > 0) {
    lines.push(`- ${session.summary.skipped} checks skipped`);
  }
  lines.push("");

  // Critical issues section
  if (session.summary.critical_issues.length > 0) {
    lines.push("## Critical Issues");
    lines.push("");
    session.summary.critical_issues.forEach((issue, i) => {
      lines.push(`${i + 1}. ${issue}`);
    });
    lines.push("");
  }

  // All findings table
  const allFailed = getAllFailed(session);
  if (allFailed.length > 0) {
    lines.push("## Issues Found");
    lines.push("");
    lines.push("| # | Page | Category | Severity | Notes |");
    lines.push("|---|------|----------|----------|-------|");
    allFailed.forEach((item, i) => {
      const emoji = SEVERITY_EMOJI[item.check.severity];
      lines.push(
        `| ${i + 1} | ${item.pageName} | ${item.check.category} | ${emoji} ${item.check.severity} | ${item.check.notes} |`
      );
    });
    lines.push("");
  }

  // Per-page details
  lines.push("## Page Details");
  lines.push("");
  for (const page of session.pages) {
    lines.push(`### ${page.name} (${page.url})`);
    lines.push("");
    if (page.viewports_tested.length > 0) {
      lines.push(
        `Viewports tested: ${page.viewports_tested.join(", ")}px`
      );
      lines.push("");
    }
    lines.push("| # | Category | Status | Severity | Notes |");
    lines.push("|---|----------|--------|----------|-------|");
    for (const check of page.checks) {
      const statusIcon =
        check.status === "pass"
          ? "✅"
          : check.status === "fail"
            ? "❌"
            : check.status === "skip"
              ? "⏭️"
              : "—";
      lines.push(
        `| ${check.id} | ${check.category} | ${statusIcon} | ${check.severity} | ${check.notes} |`
      );
    }
    lines.push("");
  }

  // Footer
  lines.push("---");
  lines.push(`*Generated by QA Voice Golem on ${new Date().toISOString()}*`);
  lines.push("");

  return lines.join("\n");
}

interface FailedItem {
  pageName: string;
  check: QACheck;
}

function getAllFailed(session: QASession): FailedItem[] {
  const items: FailedItem[] = [];
  for (const page of session.pages) {
    for (const check of page.checks) {
      if (check.status === "fail") {
        items.push({ pageName: page.name, check });
      }
    }
  }
  // Sort by severity
  items.sort(
    (a, b) =>
      SEVERITY_ORDER[a.check.severity] - SEVERITY_ORDER[b.check.severity]
  );
  return items;
}
