import { describe, it, expect } from "bun:test";
import { renderBrief } from "../brief";
import {
  createDiscoverySession,
  addChecklistItem,
  addRedFlag,
  finalizeDiscoverySession,
} from "../schemas/discovery";

describe("brief renderer", () => {
  function buildSampleSession() {
    const session = createDiscoverySession("Acme Corp");

    session.brief.project_type = "E-commerce website";
    session.brief.estimated_complexity = "medium";
    session.brief.key_requirements = [
      "Custom product catalog",
      "Stripe payment integration",
      "Admin dashboard",
    ];
    session.brief.recommended_next_steps = [
      "Send detailed proposal with timeline",
      "Schedule design review meeting",
    ];

    addChecklistItem(session, {
      category: "scope",
      question: "What type of project?",
      status: "answered",
      answer: "E-commerce site with custom CMS",
      follow_ups: [],
    });
    addChecklistItem(session, {
      category: "budget",
      question: "Budget range?",
      status: "unanswered",
      answer: "",
      follow_ups: [],
    });
    addChecklistItem(session, {
      category: "technical",
      question: "Hosting preference?",
      status: "answered",
      answer: "Vercel",
      follow_ups: ["Confirm with CTO"],
    });

    addRedFlag(session, {
      flag: "Client wants delivery in 1 week",
      severity: "high",
      suggestion: "Clarify scope — 1 week is unrealistic for full e-commerce",
    });
    addRedFlag(session, {
      flag: "Design files not ready",
      severity: "medium",
      suggestion: "Ask when Figma designs will be available",
    });

    finalizeDiscoverySession(session);
    return session;
  }

  it("renders a valid markdown brief", () => {
    const brief = renderBrief(buildSampleSession());

    expect(brief).toContain("# Project Brief: Acme Corp");
    expect(brief).toContain("**Type:** E-commerce website");
  });

  it("includes requirements as checklist", () => {
    const brief = renderBrief(buildSampleSession());

    expect(brief).toContain("## Requirements");
    expect(brief).toContain("- [ ] Custom product catalog");
    expect(brief).toContain("- [ ] Stripe payment integration");
  });

  it("includes what we learned table", () => {
    const brief = renderBrief(buildSampleSession());

    expect(brief).toContain("## What We Learned");
    expect(brief).toContain("E-commerce site with custom CMS");
    expect(brief).toContain("Vercel");
  });

  it("includes open questions from unanswered + follow-ups", () => {
    const brief = renderBrief(buildSampleSession());

    expect(brief).toContain("## Open Questions");
    expect(brief).toContain("Budget range?");
    expect(brief).toContain("Confirm with CTO");
  });

  it("includes red flags with severity", () => {
    const brief = renderBrief(buildSampleSession());

    expect(brief).toContain("## Red Flags");
    expect(brief).toContain("Client wants delivery in 1 week");
    expect(brief).toContain("high");
    expect(brief).toContain("Design files not ready");
  });

  it("includes next steps", () => {
    const brief = renderBrief(buildSampleSession());

    expect(brief).toContain("## Recommended Next Steps");
    expect(brief).toContain("Send detailed proposal");
  });

  it("includes footer", () => {
    const brief = renderBrief(buildSampleSession());

    expect(brief).toContain("Generated by Discovery Voice Golem");
  });

  it("handles empty session", () => {
    const session = createDiscoverySession("Empty Client");
    finalizeDiscoverySession(session);
    const brief = renderBrief(session);

    expect(brief).toContain("# Project Brief: Empty Client");
    expect(brief).not.toContain("## Requirements");
    expect(brief).not.toContain("## Red Flags");
  });
});
