import { describe, it, expect } from "bun:test";
import { renderReport } from "../report";
import {
  createSession,
  addPage,
  addCheck,
  finalizeSession,
} from "../schemas/checklist";

describe("report renderer", () => {
  function buildSampleSession() {
    const session = createSession("https://mysudra.co.il");
    const home = addPage(session, "/", "Homepage");
    home.viewports_tested = ["375", "768", "1440"];

    addCheck(session, home, {
      category: "accessibility",
      question: "Do inputs have labels?",
      status: "pass",
      severity: "high",
      notes: "All inputs properly labeled",
      screenshot: null,
    });
    addCheck(session, home, {
      category: "responsive",
      question: "Layout at 375px?",
      status: "fail",
      severity: "high",
      notes: "Nav overlaps logo on mobile",
      screenshot: null,
    });
    addCheck(session, home, {
      category: "interaction",
      question: "Form validation?",
      status: "fail",
      severity: "critical",
      notes: "Form submits empty",
      screenshot: null,
    });

    const about = addPage(session, "/about", "About");
    addCheck(session, about, {
      category: "content",
      question: "Any lorem ipsum?",
      status: "pass",
      severity: "high",
      notes: "Clean content",
      screenshot: null,
    });

    finalizeSession(session);
    return session;
  }

  it("renders a valid markdown report", () => {
    const report = renderReport(buildSampleSession());

    expect(report).toContain("# QA Report: mysudra.co.il");
    expect(report).toContain("**Pages:** 2");
  });

  it("includes summary section", () => {
    const report = renderReport(buildSampleSession());

    expect(report).toContain("## Summary");
    expect(report).toContain("2 checks passed");
    expect(report).toContain("2 issues found (1 critical)");
  });

  it("includes critical issues section", () => {
    const report = renderReport(buildSampleSession());

    expect(report).toContain("## Critical Issues");
    expect(report).toContain("Form submits empty");
  });

  it("includes issues table sorted by severity", () => {
    const report = renderReport(buildSampleSession());

    expect(report).toContain("## Issues Found");
    // Critical should appear before high
    const criticalIdx = report.indexOf("critical");
    const highIdx = report.indexOf("high");
    expect(criticalIdx).toBeLessThan(highIdx);
  });

  it("includes per-page details", () => {
    const report = renderReport(buildSampleSession());

    expect(report).toContain("### Homepage (/)");
    expect(report).toContain("Viewports tested: 375, 768, 1440px");
    expect(report).toContain("### About (/about)");
  });

  it("includes status icons in page details", () => {
    const report = renderReport(buildSampleSession());

    expect(report).toContain("✅"); // pass
    expect(report).toContain("❌"); // fail
  });

  it("includes footer", () => {
    const report = renderReport(buildSampleSession());

    expect(report).toContain("Generated by QA Voice Golem");
  });

  it("handles empty session", () => {
    const session = createSession("https://example.com");
    finalizeSession(session);
    const report = renderReport(session);

    expect(report).toContain("# QA Report: example.com");
    expect(report).toContain("0 checks passed");
    expect(report).not.toContain("## Critical Issues");
    expect(report).not.toContain("## Issues Found");
  });
});
