"use client";

import { createClient } from "@/lib/supabase/client";
import { uploadGraph, hasUploadedGraph } from "@/lib/supabase/graph";
import { Upload, Check, AlertCircle, Brain, LogOut, User } from "lucide-react";
import { useRouter } from "next/navigation";
import { useCallback, useEffect, useState } from "react";

export default function SettingsPage() {
  const [user, setUser] = useState<{ email: string; id: string } | null>(null);
  const [hasGraph, setHasGraph] = useState(false);
  const [uploading, setUploading] = useState(false);
  const [uploadStatus, setUploadStatus] = useState<{ ok: boolean; msg: string } | null>(null);
  const router = useRouter();
  const supabase = createClient();

  useEffect(() => {
    async function load() {
      const { data: { user } } = await supabase.auth.getUser();
      if (user) {
        setUser({ email: user.email ?? "", id: user.id });
        setHasGraph(await hasUploadedGraph());
      }
    }
    load();
  }, [supabase.auth]);

  const handleUpload = useCallback(async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    setUploading(true);
    setUploadStatus(null);

    // Validate it's valid JSON
    try {
      const text = await file.text();
      const data = JSON.parse(text);
      if (!data.nodes || !data.links) {
        setUploadStatus({ ok: false, msg: "Invalid graph: must have nodes and links arrays" });
        setUploading(false);
        return;
      }
    } catch {
      setUploadStatus({ ok: false, msg: "Invalid JSON file" });
      setUploading(false);
      return;
    }

    const { error } = await uploadGraph(file);
    if (error) {
      setUploadStatus({ ok: false, msg: error });
    } else {
      setUploadStatus({ ok: true, msg: `Uploaded graph.json (${(file.size / 1024 / 1024).toFixed(1)} MB)` });
      setHasGraph(true);
    }
    setUploading(false);
  }, []);

  async function handleSignOut() {
    await supabase.auth.signOut();
    router.push("/login");
    router.refresh();
  }

  return (
    <div className="max-w-2xl mx-auto space-y-8">
      <h1 className="text-xl font-semibold">Settings</h1>

      {/* Account */}
      <section className="space-y-3">
        <h2 className="text-sm font-medium text-muted flex items-center gap-2">
          <User className="w-4 h-4" /> Account
        </h2>
        <div className="bg-surface border border-border rounded-lg p-4 space-y-3">
          {user && (
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm">{user.email}</p>
                <p className="text-xs text-muted mt-0.5">ID: {user.id.slice(0, 8)}...</p>
              </div>
              <button
                type="button"
                onClick={handleSignOut}
                className="flex items-center gap-2 px-3 py-1.5 text-xs text-rose border border-rose/30 rounded-lg hover:bg-rose/10 transition-colors"
              >
                <LogOut className="w-3.5 h-3.5" />
                Sign out
              </button>
            </div>
          )}
        </div>
      </section>

      {/* Brain Graph Upload */}
      <section className="space-y-3">
        <h2 className="text-sm font-medium text-muted flex items-center gap-2">
          <Brain className="w-4 h-4" /> Brain Graph Data
        </h2>
        <div className="bg-surface border border-border rounded-lg p-4 space-y-4">
          <p className="text-xs text-muted">
            Upload your <code className="px-1 py-0.5 bg-background rounded text-foreground">graph.json</code> file
            generated by <code className="px-1 py-0.5 bg-background rounded text-foreground">zikaron brain-export</code>.
            This powers the Brain View 3D knowledge graph.
          </p>

          {hasGraph && (
            <div className="flex items-center gap-2 text-xs text-emerald">
              <Check className="w-3.5 h-3.5" />
              Brain graph uploaded
            </div>
          )}

          <label className="flex items-center gap-2 px-4 py-2 text-sm bg-background border border-border rounded-lg cursor-pointer hover:border-accent transition-colors w-fit">
            <Upload className="w-4 h-4" />
            {uploading ? "Uploading..." : hasGraph ? "Replace graph.json" : "Upload graph.json"}
            <input
              type="file"
              accept=".json"
              onChange={handleUpload}
              disabled={uploading}
              className="hidden"
            />
          </label>

          {uploadStatus && (
            <div className={`flex items-center gap-2 text-xs ${uploadStatus.ok ? "text-emerald" : "text-rose"}`}>
              {uploadStatus.ok ? <Check className="w-3.5 h-3.5" /> : <AlertCircle className="w-3.5 h-3.5" />}
              {uploadStatus.msg}
            </div>
          )}
        </div>
      </section>

      {/* Data Sources Info */}
      <section className="space-y-3">
        <h2 className="text-sm font-medium text-muted">Data Sources</h2>
        <div className="bg-surface border border-border rounded-lg p-4">
          <div className="space-y-2 text-xs text-muted">
            <p>The dashboard aggregates data from multiple sources:</p>
            <ul className="list-disc list-inside space-y-1 ml-2">
              <li><strong className="text-foreground">Brain View</strong> — graph.json (uploaded above) or local Zikaron daemon</li>
              <li><strong className="text-foreground">Ops / Enrichment</strong> — Zikaron daemon API (localhost:8787)</li>
              <li><strong className="text-foreground">Tokens</strong> — Supabase llm_usage table</li>
              <li><strong className="text-foreground">Backlog</strong> — Supabase backlog_items table</li>
              <li><strong className="text-foreground">Content</strong> — Supabase pipeline_runs table + render service</li>
            </ul>
          </div>
        </div>
      </section>
    </div>
  );
}
